name: Build lxml for ARM32  
  
on: [push, pull_request]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    container:  
      image: qemuusermode/ubuntu-debootstrap:focal-armhf  
      options: --platform linux/arm/v7  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  
  
    - name: Install dependencies  
      run: |  
        apt-get update  
        apt-get install -y python3.11 python3.11-venv python3.11-dev libxml2-dev libxslt1-dev libffi-dev build-essential  
  
    - name: Set up Python 3.11  
      run: |  
        python3.11 -m venv venv  
        source venv/bin/activate  
  
    - name: Install pip dependencies  
      run: |  
        pip install --upgrade pip setuptools wheel  
        pip install cython  
  
    - name: Install lxml from source  
      run: |  
        pip install lxml --only-binary :none:  
  
    - name: Verify installation  
      run: |  
        python -c "import lxml; print(lxml.__version__)"
