name: Build lxml for ARM32

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [armv7]  # ARM32架构

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          build-essential \
          libxml2-dev \
          libxslt1-dev \
          zlib1g-dev \
          python3-dev

      - name: Install lxml
        run: |
          pip install lxml --no-binary lxml

      - name: Build lxml wheel
        run: |
          mkdir -p wheelhouse
          pip wheel lxml -w wheelhouse

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: lxml-wheel
          path: wheelhouse/*.whl
